backend:
  name: github
  repo: serbia70/rusthugo
  branch: main
  base_url: https://rusthugo.vercel.app
  auth_endpoint: auth
  auth_scope: repo

publish_mode: editorial_workflow

site_url: https://rusthugo.vercel.app
display_url: https://rusthugo.vercel.app

media_folder: static/images
public_folder: /images

collections:
  - name: "posts"
    label: "博客文章"
    label_singular: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "toml-frontmatter"
    extension: "md"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "草稿", name: "draft", widget: "boolean", default: false, hint: "开启后不会发布到网站" }
      - { label: "描述", name: "description", widget: "string", required: false }
      - label: "分类信息"
        name: "taxonomies"
        widget: "object"
        fields:
          - { label: "标签", name: "tags", widget: "list", default: [] }
          - { label: "系列", name: "series", widget: "list", required: false, default: [] }
      - label: "扩展信息"
        name: "extra"
        widget: "object"
        fields:
          - { label: "封面图", name: "cover_image", widget: "string", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
